###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
      image: 'mysql:8.0'
      working_dir: /application
      volumes:
          - '.:/application'
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=corretrom
          - MYSQL_USER=sail
          - MYSQL_PASSWORD=root
      ports:
          - '3306:3306'

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8070:80

      environment:
        - PMA_ARBITRARY=1

    webserver:
      image: 'nginx:alpine'
      working_dir: /application
      volumes:
          - '.:/application'
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '8080:80'

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
          - '.:/application'
          - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
